server:
<<<<<<< HEAD
<<<<<<< HEAD
  port: 1001
spring:
  application:
    name: provider
 
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
# 服务提供者如果也需要作为消费者则可以获取注册清单，如果单纯作为服务提供者则不需要获取服务清单
      fetch-registry: false
#  服务提供者需要提供服务，所以需要将自己注册在注册中心上
      register-with-eureka: false
# 服务提供者需要把下面的实例名关闭，否则在按照消费端的代码调用是会找不到主机名（启动单实例提供者把下面注释掉）
#  instance:
#    hostname: provider1
    
=======
  port: 9999
spring:
  application:
    name: server-center2
eureka:
  instance:
    appname: center2
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
#  注册中心没必要将自己注册给自己
    register-with-eureka: false
#  注册中心不需要去检索服务，调用服务，故而不需要获取注册服务清单 
    fetch-registry: false
  server:
#  设置读取超时时间
    peer-node-read-timeout-ms: 12000
#    关闭自我保护
    enable-self-preservation: false
>>>>>>> branch 'master' of https://github.com/zuixiaoyao001/eureka-service-center2.git
=======
  port: 9999
spring:
  application:
    name: server-center2
eureka:
  instance:
    appname: center2
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
#  注册中心没必要将自己注册给自己
    register-with-eureka: false
#  注册中心不需要去检索服务，调用服务，故而不需要获取注册服务清单 
    fetch-registry: false
  server:
#  设置读取超时时间
    peer-node-read-timeout-ms: 12000
#    关闭自我保护
    enable-self-preservation: false
>>>>>>> branch 'master' of https://github.com/zuixiaoyao001/eureka-service-center2.git
